apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: builds.kpack.io
spec:
  group: kpack.io
  versions:
    - name: v1alpha2
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          # https://github.com/pivotal/kpack/blob/main/docs/build.md
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
              properties:
                annotations:
                  type: object
                  properties:
                    image.kpack.io/buildChanges:
                      type: string
            spec:
              type: object
              properties:
                tags:
                  type: array
                  items:
                    type: string
                serviceAccountName:
                  type: string
                builder:
                  type: object
                source:
                  type: object
                  properties:
                    git:
                      type: object
                      properties:
                        url:
                          type: string
                        revision:
                          type: string
                    subPath:
                      type: string
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      lastTransitionTime:
                        type: string
                      status:
                        type: string
                      type:
                        type: string
                latestImage:
                  type: string
          type: object
      subresources:
        status: { }
      additionalPrinterColumns:
        - name: Image
          type: string
          jsonPath: ".status.latestImage"
        - name: Succeeded
          type: string
          jsonPath: ".status.conditions[?(@.type==\"Succeeded\")].status"
  names:
    kind: Build
    listKind: BuildList
    singular: build
    plural: builds
    shortNames:
      - cnbbuild
      - cnbbuilds
      - bld
      - blds
    categories:
      - kpack
  scope: Namespaced