/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.vmware.tanzu.kpackghstatusupdater.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * V1alpha2BuildSpecSource
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-11-27T15:06:33.623Z[Etc/UTC]")
public class V1alpha2BuildSpecSource {
    public static final String SERIALIZED_NAME_GIT = "git";
    public static final String SERIALIZED_NAME_SUB_PATH = "subPath";
    @SerializedName(SERIALIZED_NAME_GIT)
    private V1alpha2BuildSpecSourceGit git;
    @SerializedName(SERIALIZED_NAME_SUB_PATH)
    private String subPath;


    public V1alpha2BuildSpecSource git(V1alpha2BuildSpecSourceGit git) {

        this.git = git;
        return this;
    }

    /**
     * Get git
     *
     * @return git
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha2BuildSpecSourceGit getGit() {
        return git;
    }


    public void setGit(V1alpha2BuildSpecSourceGit git) {
        this.git = git;
    }


    public V1alpha2BuildSpecSource subPath(String subPath) {

        this.subPath = subPath;
        return this;
    }

    /**
     * Get subPath
     *
     * @return subPath
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getSubPath() {
        return subPath;
    }


    public void setSubPath(String subPath) {
        this.subPath = subPath;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1alpha2BuildSpecSource v1alpha2BuildSpecSource = (V1alpha2BuildSpecSource) o;
        return Objects.equals(this.git, v1alpha2BuildSpecSource.git) &&
                Objects.equals(this.subPath, v1alpha2BuildSpecSource.subPath);
    }

    @Override
    public int hashCode() {
        return Objects.hash(git, subPath);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1alpha2BuildSpecSource {\n");
        sb.append("    git: ").append(toIndentedString(git)).append("\n");
        sb.append("    subPath: ").append(toIndentedString(subPath)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

