/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.vmware.tanzu.kpackghstatusupdater.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * V1alpha2BuildStatus
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-11-27T15:06:33.623Z[Etc/UTC]")
public class V1alpha2BuildStatus {
    public static final String SERIALIZED_NAME_CONDITIONS = "conditions";
    public static final String SERIALIZED_NAME_LATEST_IMAGE = "latestImage";
    @SerializedName(SERIALIZED_NAME_CONDITIONS)
    private List<V1alpha2BuildStatusConditions> conditions = null;
    @SerializedName(SERIALIZED_NAME_LATEST_IMAGE)
    private String latestImage;


    public V1alpha2BuildStatus conditions(List<V1alpha2BuildStatusConditions> conditions) {

        this.conditions = conditions;
        return this;
    }

    public V1alpha2BuildStatus addConditionsItem(V1alpha2BuildStatusConditions conditionsItem) {
        if (this.conditions == null) {
            this.conditions = new ArrayList<>();
        }
        this.conditions.add(conditionsItem);
        return this;
    }

    /**
     * Get conditions
     *
     * @return conditions
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public List<V1alpha2BuildStatusConditions> getConditions() {
        return conditions;
    }


    public void setConditions(List<V1alpha2BuildStatusConditions> conditions) {
        this.conditions = conditions;
    }


    public V1alpha2BuildStatus latestImage(String latestImage) {

        this.latestImage = latestImage;
        return this;
    }

    /**
     * Get latestImage
     *
     * @return latestImage
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getLatestImage() {
        return latestImage;
    }


    public void setLatestImage(String latestImage) {
        this.latestImage = latestImage;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1alpha2BuildStatus v1alpha2BuildStatus = (V1alpha2BuildStatus) o;
        return Objects.equals(this.conditions, v1alpha2BuildStatus.conditions) &&
                Objects.equals(this.latestImage, v1alpha2BuildStatus.latestImage);
    }

    @Override
    public int hashCode() {
        return Objects.hash(conditions, latestImage);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1alpha2BuildStatus {\n");
        sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
        sb.append("    latestImage: ").append(toIndentedString(latestImage)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

