/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.vmware.tanzu.kpackghstatusupdater.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * V1alpha2BuildStatusConditions
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-11-27T15:06:33.623Z[Etc/UTC]")
public class V1alpha2BuildStatusConditions {
    public static final String SERIALIZED_NAME_LAST_TRANSITION_TIME = "lastTransitionTime";
    public static final String SERIALIZED_NAME_STATUS = "status";
    public static final String SERIALIZED_NAME_TYPE = "type";
    @SerializedName(SERIALIZED_NAME_LAST_TRANSITION_TIME)
    private String lastTransitionTime;
    @SerializedName(SERIALIZED_NAME_STATUS)
    private String status;
    @SerializedName(SERIALIZED_NAME_TYPE)
    private String type;


    public V1alpha2BuildStatusConditions lastTransitionTime(String lastTransitionTime) {

        this.lastTransitionTime = lastTransitionTime;
        return this;
    }

    /**
     * Get lastTransitionTime
     *
     * @return lastTransitionTime
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getLastTransitionTime() {
        return lastTransitionTime;
    }


    public void setLastTransitionTime(String lastTransitionTime) {
        this.lastTransitionTime = lastTransitionTime;
    }


    public V1alpha2BuildStatusConditions status(String status) {

        this.status = status;
        return this;
    }

    /**
     * Get status
     *
     * @return status
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getStatus() {
        return status;
    }


    public void setStatus(String status) {
        this.status = status;
    }


    public V1alpha2BuildStatusConditions type(String type) {

        this.type = type;
        return this;
    }

    /**
     * Get type
     *
     * @return type
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getType() {
        return type;
    }


    public void setType(String type) {
        this.type = type;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1alpha2BuildStatusConditions v1alpha2BuildStatusConditions = (V1alpha2BuildStatusConditions) o;
        return Objects.equals(this.lastTransitionTime, v1alpha2BuildStatusConditions.lastTransitionTime) &&
                Objects.equals(this.status, v1alpha2BuildStatusConditions.status) &&
                Objects.equals(this.type, v1alpha2BuildStatusConditions.type);
    }

    @Override
    public int hashCode() {
        return Objects.hash(lastTransitionTime, status, type);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1alpha2BuildStatusConditions {\n");
        sb.append("    lastTransitionTime: ").append(toIndentedString(lastTransitionTime)).append("\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

